version: "2"

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  php71-apache:
    image: php71-apache
    build:
      context: .
      args:
        PHP_VERSION: 7.1-apache
    volumes:
      - ./main:/var/www
    environment:
      VIRTUAL_HOST: php71.local.entwickl.de
#
#  php71-cli:
#    image: php71-cli
#    build:
#      context: .
#      args:
#        PHP_VERSION: 7.1-cli
