version: "2"

services:
  php56-apache:
    build:
      context: .
      dockerfile: php56-apache/Dockerfile
    image: php56-apache
    ports:
      - "8056:80"
    volumes:
      - ./www:/var/www
    environment:
      - APP_ENV=dev

  php70-apache:
    build:
      context: .
      dockerfile: php70-apache/Dockerfile
    image: php70-apache
    ports:
      - "8070:80"
    volumes:
      - ./www:/var/www
    environment:
      - APP_ENV=dev

  php71-apache:
    build:
      context: .
      dockerfile: php71-apache/Dockerfile
    image: php71-apache
    ports:
      - "8071:80"
    volumes:
      - ./www:/var/www
    environment:
      - APP_ENV=dev

  php72-apache:
    build:
      context: .
      dockerfile: php72-apache/Dockerfile
    image: php72-apache
    ports:
      - "8072:80"
    volumes:
      - ./www:/var/www
    environment:
      - APP_ENV=dev