version: "2"

services:
  php56-apache:
    build:
      context: apache
      dockerfile: Dockerfile
    ports:
      - "8056:80"
    volumes:
      - ./www:/var/www
    environment:
      - APP_ENV=dev

  php70-apache:
    build:
      context: apache
      dockerfile: Dockerfile
    ports:
      - "8070:80"
    volumes:
      - ./www:/var/www
    environment:
      - APP_ENV=dev

  php71-apache:
    build:
      context: apache
      dockerfile: Dockerfile
    ports:
      - "8071:80"
    volumes:
      - ./www:/var/www
    environment:
      - APP_ENV=dev

  php72-apache:
    build:
      context: apache
      dockerfile: Dockerfile
    ports:
      - "8072:80"
    volumes:
      - ./www:/var/www
    environment:
      - APP_ENV=dev