version: "2"

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  7.4-apache-debian-buster:
    build:
      dockerfile: php/7.4/apache/debian/buster/Dockerfile
      context: .
    environment:
      VIRTUAL_HOST: 7.4-apache-debian-buster.127.0.0.1.xip.io
    volumes:
      - ./main:/app/main

  7.4-cli-debian-buster:
    build:
      dockerfile: php/7.4/cli/debian/buster/Dockerfile
      context: .
    volumes:
      - ./main:/app/main

  7.4-apache-ubuntu-bionic:
    build:
      dockerfile: php/7.4/apache/ubuntu/bionic/Dockerfile
      context: .
    environment:
      VIRTUAL_HOST: 7.4-apache-ubuntu-bionic.127.0.0.1.xip.io
    volumes:
      - ./main:/app/main

  7.4-cli-ubuntu-bionic:
    build:
      dockerfile: php/7.4/cli/ubuntu/bionic/Dockerfile
      context: .
    volumes:
      - ./main:/app/main