version: "2"

services:
  php56-apache:
    build:
      context: apache
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 5.6
    ports:
      - 8056:80
    volumes:
      - ./www:/var/www

  php70-apache:
    build:
      context: apache
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 7.0
    ports:
      - 8070:80
    volumes:
      - ./www:/var/www

  php71-apache:
    build:
      context: apache
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 7.1
    ports:
      - 8071:80
    volumes:
      - ./www:/var/www

  php72-apache:
    build:
      context: apache
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 7.2
    ports:
      - 8072:80
    volumes:
      - ./www:/var/www