version: "2"

services:
  php56-apache:
    build:
      context: apache
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 5.6
        APACHE_RUN_UID: 5600
        APACHE_RUN_GID: 1056
    ports:
      - 8056:80
    volumes:
      - ./www:/var/www

  php70-apache:
    build:
      context: apache
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 7.0
        APACHE_RUN_UID: 7000
        APACHE_RUN_GID: 1070
    ports:
      - 8070:80
    volumes:
      - ./www:/var/www

  php71-apache:
    build:
      context: apache
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 7.1
        APACHE_RUN_UID: 7100
        APACHE_RUN_GID: 1071
    ports:
      - 8071:80
    volumes:
      - ./www:/var/www

  php72-apache:
    build:
      context: apache
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 7.2
        APACHE_RUN_UID: 7200
        APACHE_RUN_GID: 1072
    ports:
      - 8072:80
    volumes:
      - ./www:/var/www