name: Release

on:
  push:

jobs:
  _74:
    name: Release 7.4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: elnebuloso/github-action-phing@master
        with:
          target: 7.4-apache-debian-buster
      - uses: elnebuloso/github-action-phing@master
        with:
          target: 7.4-cli-debian-buster