name: Release

on:
  push:

jobs:
  _74:
    name: Release 7.4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: elnebuloso/github-action-phing@master
        with:
          target: 7.4-apache-debian-buster
      - name: run structure tests
        uses: plexsystems/container-structure-test-action@v0.1.0
        with:
          image: 7.4-apache-debian-buster
          config: tests/all/tests.yaml

      - uses: elnebuloso/github-action-phing@master
        with:
          target: 7.4-cli-debian-buster
      - name: run structure tests
        uses: plexsystems/container-structure-test-action@v0.1.0
        with:
          image: 7.4-cli-debian-buster
          config: tests/all/tests.yaml