name: Release

on:
  push:

jobs:
  main:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: elnebuloso/github-action-phing@master
        with:
          target: project:help
      - uses: elnebuloso/github-action-phing@master
        with:
          target: properties:ci:git
      - uses: elnebuloso/github-action-phing@master
        with:
          target: properties:ci:gitversion
      - uses: elnebuloso/github-action-phing@master
        with:
          target: properties:ci:fileversion
      - uses: elnebuloso/github-action-phing@master
        with:
          target: |
            properties:ci:gitversion
            properties:ci:fileversion
